name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}

    - name: Run the Docker image
      run: docker run my-image-name:${{ github.sha }} Hello ${{ github.sha }}
