name: Docker Image CI

on: [push]


jobs:

  build:

    runs-on: windows-2019
    
    strategy:
      matrix:
        python-version:
          - '2.7.11'
#          - '3.6.8'
#          - '3.7.5'
      fail-fast: false    
      

    steps:
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
        
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --build-arg python=${{ matrix.python-version }} . --file Dockerfile --tag rez-test:${{ github.sha }}

    - name: Run the Docker image
      run: docker run my-image-name:${{ github.sha }} ${{ github.repository }} ${{ github.sha }}
